In [11]:
import cv2
import numpy as np
from scipy.signal import convolve2d

In [2]:
image=np.array([[120, 125, 115],
                 [128, 133, 122],
                 [112, 118, 126]])

In [3]:
print("Image:")
print(image)

Image:
[[120 125 115]
 [128 133 122]
 [112 118 126]]


In [5]:
sobel_x=np.array([[-1, 0, 1],
                  [-2, 0, 2],
                [-1, 0, 1]])

In [8]:
print("sobel_x")
sobel_x

sobel_x


array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [7]:
sobel_y=np.array([[-1, -2, -1],
                 [0, 0, 0],
                 [1, 2, 1]])

In [9]:
print("sobel_y")
sobel_y

sobel_y


array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  2,  1]])

In [13]:
gradient_x = convolve2d(image, sobel_x, mode='same', boundary='wrap')
gradient_y = convolve2d(image, sobel_y, mode='same', boundary='wrap')

In [15]:
print("gradient_x")
gradient_x

gradient_x


array([[-23,   2,  21],
       [-24,   3,  21],
       [ -5, -17,  22]])

In [16]:
print("gradient_y")
gradient_y

gradient_y


array([[-43, -42, -23],
       [ 12,  11,  -7],
       [ 31,  31,  30]])

In [17]:
gradient_magnitude = np.sqrt(gradient_x**2 + gradient_y**2)

In [19]:
print("Gradient Magnitude")
gradient_magnitude

Gradient Magnitude


array([[48.76474136, 42.04759208, 31.144823  ],
       [26.83281573, 11.40175425, 22.13594362],
       [31.40063694, 35.35533906, 37.20215048]])